config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'public/pages#home'
  devise_for :users
  
  namespace :public do
  	get 'home', to: :home, controller: 'pages'
    get 'service', to: :service, controller: 'pages'
    get 'login', to: :login, controller: 'pages'
  end
  
  namespace :private do
  	resources :services
  	resources :comments
  	resources :classifications
    resources :services_classifications
  	get 'approve_comment', to: :approve_comment, controller: 'comments'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classification.rb
class Classification < ApplicationRecord
	has_many :services_classifications
	has_many :services, :through => :services_classifications

	validates :title,
						:description,
						presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :service

	validates :title,
						:body,
						:status,
						:service_id,
						presence: true

	enum status: [:Aprobado, :No_aprobado]
end

app/models/promotion.rb
class Promotion < ApplicationRecord
	has_many :services_promotions
	has_many :services, :through => :services_promotions

	validates :title,
						presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :comments
	has_many :services_promotions
	has_many :services_classifications
	has_many :classifications, :through => :services_classifications
	has_many :promotions,			 :through => :services_promotions

	validates :name,
						:price,
						:invitation,
						:description,
						presence: true
end

app/models/services_classification.rb
class ServicesClassification < ApplicationRecord
	belongs_to :service
	belongs_to :classification

	validates :service_id,
						:classification_id,
						presence: true
end

app/models/services_promotion.rb
class ServicesPromotion < ApplicationRecord
	belongs_to :service
	belongs_to :promotion

	validates :service_id,
						:promotion_id,
						presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/private/base_controller.rb
class Private::BaseController < ApplicationController
	layout 'private_layout'

	before_action :authenticate_user!, except: [:create]

end

app/controllers/private/classifications_controller.rb
class Private::ClassificationsController < Private::BaseController

	def index
		@classifications = Classification.all
	end

	def new
		@classification = Classification.new
	end

	def create
		@classification = Classification.new(classification_params)
		if @classification.save
			redirect_to private_classifications_path
		else
			render :new
		end
	end

	def destroy
		@services_classifications = ServicesClassification.where(classification_id: params[:id])
		@services_classifications.destroy_all
		@classification = Classification.find(params[:id])
		@classification.delete
		redirect_to private_classifications_path
	end

	private

	def classification_params
		params.require(:classification).permit(:title, :description)
	end
end

app/controllers/private/comments_controller.rb
class Private::CommentsController < Private::BaseController

	def index
		@comments = Comment.where(status: params[:status]).reverse
		@count_approved_comments = Comment.where(status: 0).count
		@count_to_approve_comments = Comment.where(status: 1).count
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to private_comments_path status: 1
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.save
		redirect_to public_service_path(id: @comment.service_id)
	end

	def approve_comment
		@comment = Comment.find(params[:comment])
		@comment.status = 0
		@comment.save
		redirect_to private_comments_path status: 0
	end

	private

	def comment_params
		params.require(:comment).permit(:title, :body, :users_name, :status, :service_id)
	end
end

app/controllers/private/services_classifications_controller.rb
class Private::ServicesClassificationsController < Private::BaseController

	def new
		@services_classification = ServicesClassification.new
		@services_classification.classification_id = params[:classification_id]
		@classification = Classification.find(params[:classification_id])
		if ServicesClassification.where(classification_id: params[:classification_id]).count > 0
			@services = Service.where("id not in (#{ServicesClassification.where(classification_id: params[:classification_id]).pluck(:service_id).join(',')})")
		else
			@services = Service.all
		end
	end

	def create
		@services_classification = ServicesClassification.new(service_classification_params)
		if @services_classification.save
			redirect_to private_classifications_path
		else
			render :new
		end
	end

	def destroy
		@services_classification = ServicesClassification.find(params[:id])
		@services_classification.delete
		redirect_to private_classifications_path
	end

	private

	def service_classification_params
		creation_params = { service_id: params[:service_id], classification_id: params[:classification_id] }
	end
end

app/controllers/private/services_controller.rb
class Private::ServicesController < Private::BaseController

	def index
		params[:q] ||= {}
		@q = Service.ransack(params[:q])
		@services = @q.result(distinct: true)
	end

	def show
		@service = Service.find(params[:id])
	end

	def new
		@service = Service.new
	end

	def create
		params[:service][:name].strip!
		uploaded_io = params[:service][:image]
		uploaded_io.original_filename = "service_#{params[:service][:name].gsub(' ', '_').camelize}.jpg"
		params[:service][:image] = "service_#{params[:service][:name].gsub(' ', '_').camelize}.jpg"
		File.open(Rails.root.join('app', 'assets', 'images', 'services', uploaded_io.original_filename), 'wb') do |file|
			file.write(uploaded_io.read)
		end
		@service = Service.new(service_params)
		if @service.save
			redirect_to [:private, @service]
		else
			render :new
		end
	end

	def edit
		@service = Service.find(params[:id])
	end

	def update
		params[:service][:name].strip!
		uploaded_io = params[:service][:image]
		uploaded_io.original_filename = "service_#{params[:service][:name].gsub(' ', '_').camelize}.jpg"
		params[:service][:image] = "service_#{params[:service][:name].gsub(' ', '_').camelize}.jpg"
		File.open(Rails.root.join('app', 'assets', 'images', 'services', uploaded_io.original_filename), 'wb') do |file|
			file.write(uploaded_io.read)
		end
		@service = Service.find(params[:id])
		if @service.update(service_params)
			redirect_to [:private, @service]
		else
			render :edit
		end
	end

	def destroy
		@services_classifications = ServicesClassification.where(service_id: params[:id])
		@services_classifications.destroy_all
		@comments = Comment.where(service_id: params[:id])
		@comments.destroy_all
		@service = Service.find(params[:id])
		@service.destroy
		redirect_to private_services_path
	end

	private

	def service_params
		params.require(:service).permit(:name, :price, :invitation, :description, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_icon(icon)
    return "<i class='fa fa-#{icon} fa-fw'></i>"
  end

  def fa_icon_2x(icon)
    return "<i class='fa fa-#{icon} fa-2x'></i>"
  end

  def fa_icon_stack2(icon)
    return "<i class='fa fa-#{icon} fa-stack-2x'></i>"
  end

  def fa_icon_stack1(icon)
    return "<i class='fa fa-#{icon} fa-stack-1x'></i>"
  end

  def fa_icon_lg(icon)
    return "<i class='fa fa-#{icon} fa-lg'></i>"
  end
end

app/helpers/private/base_helper.rb
module Private::BaseHelper
end

app/helpers/private/classifications_helper.rb
module Private::ClassificationsHelper
end

app/helpers/private/comments_helper.rb
module Private::CommentsHelper
end

app/helpers/private/services_classifications_helper.rb
module Private::ServicesClassificationsHelper
end

app/helpers/private/services_helper.rb
module Private::ServicesHelper
end

app/views/layouts/_private_footer.html.slim
footer.footer-content
	.container-fluid.copyright-content
		| Foot Spa Podólogos © 2018 derechos reservados.

app/views/layouts/_private_nav_bar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
	.container-fluid
		.navbar-header
			button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#collapsable-navbar' aria-expanded='false'
				span.sr-only
					| Toggle navigation
				span.icon-bar
				span.icon-bar
				span.icon-bar
			a.navbar-brand href='#'
				= image_tag 'logo_navbar.png', alt: 'Brand', class: 'navbar-header-logo'
				span.navbar-header-text
					| PodoRuiz
		#collapsable-navbar.collapse.navbar-collapse
			ul.nav.navbar-nav.navbar-right
				- if controller_name == 'services'
					li.active
						= link_to private_services_path
							| Servicios
				- else
					li
						= link_to private_services_path
							| Servicios
				- if controller_name == 'comments'
					li.active
						= link_to private_comments_path(status: 1)
							| Comentarios
				- else
					li
						= link_to private_comments_path(status: 1)
							| Comentarios
				/- if controller_name == 'promotions'
					li.active
						a href='#'
							| Promociones
				/- else
					li
						a href='#'
							| Promociones
				- if controller_name == 'classifications'
					li.active
						= link_to private_classifications_path
							| Clasificaciones
				- else
					li
						= link_to private_classifications_path
							| Clasificaciones

				li
					= link_to public_home_path
						| Público
				li.login-btn
					= link_to destroy_user_session_path, method: :delete
						i.fa.fa-sign-out.fa-lg
						/| Cerrar Sesión

app/views/layouts/_public_footer.html.slim
footer.footer-content
	.container-fluid
		.row
			.col-xs-offset-1.col-xs-2.footer-logo-col.vcenter
				= image_tag 'Logo.png', class: 'footer-logo'
			.col-xs-6.footer-contact-info-col.vcenter
				h4
					= fa_icon 'map-marker'
					|  5 de Febreo #1557, Col. Nuevo Repueblo
					br
					br
					= fa_icon 'mobile'
					|  +52 1 818 020 9010
					br
					br
					= fa_icon 'phone'
					|  (81) 8129 0711
			.col-xs-2.footer-social-networks-col.vcenter
				= link_to '#'
					span.fa-stack.fa-lg
						i.fa.fa-circle-thin.fa-stack-2x
						i.fa.fa-facebook.fa-stack-1x
				br
				= link_to '#'
					span.fa-stack.fa-lg
						i.fa.fa-circle-thin.fa-stack-2x
						i.fa.fa-twitter.fa-stack-1x
				br
				= link_to '#'
					span.fa-stack.fa-lg
						i.fa.fa-circle-thin.fa-stack-2x
						i.fa.fa-whatsapp.fa-stack-1x
	.container-fluid.copyright-content
		| Foot Spa Podólogos © 2018 derechos reservados.

app/views/layouts/_public_nav_bar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
	.container-fluid
		.navbar-header
			button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#collapsable-navbar' aria-expanded='false'
				span.sr-only
					| Toggle navigation
				span.icon-bar
				span.icon-bar
				span.icon-bar
			a.navbar-brand href='#'
				= image_tag 'logo_navbar.png', alt: 'Brand', class: 'navbar-header-logo'
				span.navbar-header-text
					| PodoRuiz
		#collapsable-navbar.collapse.navbar-collapse
			ul.nav.navbar-nav.navbar-right.public-navbar-ul
				
				- if action_name == 'home'
					li.active
						= link_to public_home_path
							| Inicio
				- else
					li
						= link_to public_home_path
							| Inicio

				- classifications = Classification.all

				- classifications.each do |classification|
					- services = Service.joins(services_classifications: :classification).where("classifications.id = #{classification[:id]}")
					li.dropdown
						a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'
							= "#{classification[:title]} "
							= fa_icon 'angle-down'
						ul.dropdown-menu
							- services.each do |service|
								- if action_name == 'service' && params[:name] == service
									li.active
										= link_to public_service_path(id: service[:id])
											= service[:name]
								- else
									li
										= link_to public_service_path(id: service[:id])
											= service[:name]

				/- services = Service.all.pluck(:name)
				
				/- if services.count <= 4
					- services.each do |service|
						- if action_name == 'service' && params[:name] == service
							li.active
								= link_to public_service_path(name: service)
									= service
						- else
							li
								= link_to public_service_path(name: service)
									= service
				/- else
					li.dropdown
						a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'
							| Servicios 
							= fa_icon 'angle-down'
						ul.dropdown-menu
							- services.each do |service|
								- if action_name == 'service' && params[:name] == service
									li.active
										= link_to public_service_path(name: service)
											= service
								- else
									li
										= link_to public_service_path(name: service)
											= service

				- if user_signed_in?
					li
						= link_to private_services_path
							| Administración

				li.login-btn
					- if user_signed_in?
						= link_to destroy_user_session_path, method: :delete
							i.fa.fa-sign-out.fa-lg
							/| Cerrar Sesión
					- else
						= link_to new_user_session_path
							i.fa.fa-sign-in.fa-lg
							/| Iniciar Sesión

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootSpaPodologos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.slim
doctype html
html
  head
    title
    	|	FootSpaPodologos
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag		 'devise'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/layouts/private_layout.html.slim
doctype html
html
  head
    title
    	|	FootSpaPodologos
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
		= render partial: 'layouts/private_nav_bar'
		= yield
		= render partial: 'layouts/private_footer'

app/views/layouts/public_layout.html.slim
doctype html
html
  head
    title
    	|	FootSpaPodologos
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
  	= render partial: 'layouts/public_nav_bar'
    = yield
    = render partial: 'layouts/public_footer'

app/views/private/classifications/index.html.slim
header.classifications-header
	.content-header-title
		h1
			= fa_icon 'bookmark'
			|  Clasificaciones

.container_fluid.classifications-content
	.row.new-classification-btn-container
		.col-xs-12
			= link_to new_private_classification_path, class: 'btn btn-amethyst'
				= fa_icon 'pencil'
				|  Nueva Clasificación
	- @classifications.each do |classification|
		- services = Service.joins(:services_classifications).where("services_classifications.classification_id = #{classification.id}")
		.row
			.col-xs-offset-1.col-xs-10
				.panel
					.panel-heading.clearfix
						= fa_icon 'folder-open-o'
						= " #{classification.title}"
						= link_to private_classification_path(classification), method: :delete, class: 'btn btn-alizarin pull-right', data: { confirm: '¿Seguro que desea eliminar esta clasificación?' }
							= fa_icon 'trash'
						= link_to new_private_services_classification_path(classification_id: classification.id), class: 'btn btn-positive pull-right btn-add-service'
							= fa_icon 'plus'

					ul.list-group
						- services.each do |service|
							li.list-group-item
								.row
									.col-xs-3.service-image-col
										- if service.image.blank? || !File.exist?(Rails.root.join('app', 'assets', 'images', 'services', service.image))
											= image_tag 'placeholder.png', class: 'service-image'
										- else
											= image_tag "services/#{service.image}", class: 'service-image'
									.col-xs-6.service-description-col
										h4
											= service.name
										= service.invitation
									.col-xs-3.service-actions-col
										.btn-group
											button.btn.btn-turquoise.dropdown-toggle data-toggle='dropdown' type='button'
												= fa_icon 'eye'
												|  Acciones
												= fa_icon 'angle-down'
											ul.dropdown-menu role='menu'
												li
													= link_to private_services_classification_path(ServicesClassification.find_by(service_id: service.id, classification_id: classification.id).id), method: :delete
														= fa_icon 'chain-broken'
														|  Desenlazar
												li
													= link_to private_service_path(service.id)
														= fa_icon 'leaf'
														|  Ver Servicio

app/views/private/classifications/new.html.slim
header.new-classification-header
	.content-header-title
		h1
			= fa_icon 'pencil'
			|  Nueva Clasificación

.container_fluid.new-classification-form-content
	= form_for [:private, @classification] do |f|
		form
			.row
				.col-xs-offset-2.col-xs-8
					.form-group
						= f.label :title
							| Título
						= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Nombre de la clasificación'
			.row
				.col-xs-offset-2.col-xs-8
					.form-group
						= f.label :description
							| Descripción
						= f.text_area :description, class: 'form-control', placeholder: 'Breve descripción de lo que se trata esta clasificación.'
			.row
				.col-xs-offset-2.col-xs-8.new-classifications-form-btns-col
					= f.submit 'Guardar', class: 'btn btn-positive btn-save'
					= link_to private_classifications_path, class: 'btn btn-alizarin'
						| Cancelar

app/views/private/comments/index.html.slim
header.comments-header
	.comments-header-title
		h1
			= fa_icon 'comments'
			|  Comentarios

.container_fluid.comments-content
	.row.comments-top-buttons
		.col-xs-12
			.btn.btn-to-approve-comments
				= link_to private_comments_path(status: 1)
					= fa_icon 'pencil-square-o'
					= " Pendientes (#{@count_to_approve_comments})"
					
			.btn.btn-approved-comments
				= link_to private_comments_path(status: 0)
					= fa_icon 'check-square-o'
					= " Aprobados (#{@count_approved_comments})"

	- @comments.each_with_index do |comment, index|
		.row
			.col-xs-offset-1.col-xs-2
				= image_tag "users/0#{comment.id % 10}.png", class: 'user-image'
			.col-xs-7
				.panel.arrow
					.panel-body
						.row
							.col-xs-3
								strong
									= comment.users_name
								br
								= Service.find(comment.service_id).name
								br
								small
									= comment.created_at.strftime('%d/%m/%Y')
							.col-xs-7
								= comment.body
							.col-xs-2.comments-btns
								- if comment.status == 'No_aprobado'
									.btn.btn-approve-comment
										= link_to private_approve_comment_path(comment: comment.id)
											= fa_icon 'check'
											|  Aprobar
								.btn.btn-deny-comment
									= link_to private_comment_path(comment.id), method: :delete
										= fa_icon 'times'
										|  Eliminar

app/views/private/services/edit.html.slim
header.edit-service-header
	.edit-service-header-title
		h1
			= fa_icon 'pencil-square-o'
			= " Editar #{@service.name}"

.container_fluid.edit-service-form-content
	= form_for [:private, @service], html: { multipart: true } do |f|
		form
			.row
				.col-xs-offset-2.col-xs-6
					.form-group
						= f.label :name
							| Nombre
						= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Nombre del servicio'
				.col-xs-2
					.form-group
						= f.label :price
							| Precio
						.input-group
							.input-group-addon
								|$
							= f.number_field :price, class: 'form-control', placeholder: 'Precio del servicio'
			.row
				.col-xs-offset-2.col-xs-8
					.form-group
						= f.label :invitation
							| Invitación
						= f.text_field :invitation, class: 'form-control', placeholder: 'Invitación a contratar el servicio'
					.form-group
						= f.label :description
							| Descripción
						= f.text_area :description, class: 'form-control', placeholder: 'Descripción del nuevo servicio.'

					.form-group
						= f.label :image
							| Imagen
						= f.file_field :image
			.row
				.col-xs-offset-2.col-xs-8.edit-service-form-btns-col
					= f.submit 'Guardar', class: 'btn btn-positive btn-save'
					= link_to private_service_path, class: 'btn btn-alizarin'
						| Cancelar

app/views/private/services/index.html.slim
header.services-header
	.services-header-title
		h1
			= fa_icon 'leaf'
			|  Servicios
	br
	.row.search-container
		.col-xs-offset-2.col-xs-8
			.panel
				.panel-heading.clearfix
					= fa_icon 'search'
					|  Búsqueda
					= link_to new_private_service_path, class: 'btn btn-turquoise pull-right'
						= fa_icon 'plus'
				.panel-body
					.form
						= search_form_for @q, url: private_services_path do |f|
							.form-body
								.row
									.col-xs-4
										.form-group
											= f.label :name_cont, 'Nombre del servicio'
											= f.search_field :name_cont, class: 'form-control'
									.col-xs-4
										.form-group
											= f.label :price_eq, 'Precio'
											= f.select :price_eq, options_for_select(Service.distinct.order(price: :asc).pluck(:price)), { include_blank: true }, class: 'form-control'
									.col-xs-4
										.form-group
											br
											= f.submit 'Buscar', class: 'btn btn-positive', style: 'margin-right: 10px;'
											= link_to 'Limpiar', request.path, class: 'btn btn-default'

.container_fluid.content
	.row
		- @services.each_with_index do |service, index|
			.col-xs-4
				= link_to private_service_path(service), class: 'thumbnail'
					- if service.image.blank? || !File.exist?(Rails.root.join('app', 'assets', 'images', 'services', service.image))
						= image_tag 'placeholder.png', class: 'thumbnail-image'
					- else
						= image_tag "services/#{service.image}", class: 'thumbnail-image'
					.caption
						strong
							= "#{service.name}"
					.caption
						= "$#{service.price}"

app/views/private/services/new.html.slim
header.new-service-header
	.new-service-header-title
		h1
			= fa_icon 'pencil'
			|  Nuevo servicio

.container_fluid.new-service-form-content
	= form_for [:private, @service], html: { multipart: true } do |f|
		form
			.row
				.col-xs-offset-2.col-xs-6
					.form-group
						= f.label :name
							| Nombre
						= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Nombre del servicio'
				.col-xs-2
					.form-group
						= f.label :price
							| Precio
						.input-group
							.input-group-addon
								|$
							= f.number_field :price, class: 'form-control', placeholder: 'Precio del servicio'
			.row
				.col-xs-offset-2.col-xs-8
					.form-group
						= f.label :invitation
							| Invitación
						= f.text_field :invitation, class: 'form-control', placeholder: 'Invitación a contratar el servicio'
					.form-group
						= f.label :description
							| Descripción
						= f.text_area :description, class: 'form-control', placeholder: 'Descripción del nuevo servicio.'

					.form-group
						= f.label :image
							| Imagen
						= f.file_field :image
			.row
				.col-xs-offset-2.col-xs-8.new-service-form-btns-col
					= f.submit 'Guardar', class: 'btn btn-positive btn-save'
					= link_to private_services_path, class: 'btn btn-alizarin'
						| Cancelar

app/views/private/services/show.html.slim
header.show-services-header
	.services-header-title
		h1
			= fa_icon 'leaf'
			= " #{@service.name}"

.container-fluid.content-show
	.row.show-service-top-buttons
		.col-xs-12
			= link_to edit_private_service_path(@service), class: 'btn btn-peter-river left-btn-service'
				= fa_icon 'pencil-square-o'
				|  Editar

			=link_to private_service_path(@service), method: :delete, class: 'btn btn-alizarin left-btn-service', data: { confirm: '¿Seguro que desea eliminar este servicio?' }
				= fa_icon 'trash'
				|  Eliminar

			=link_to private_services_path, class: 'btn btn-positive'
				= fa_icon 'angle-double-left'
				|  Regresar

	.row
		.col-xs-1
		.col-xs-4.vcenter
			- if @service.image.blank? || !File.exist?(Rails.root.join('app', 'assets', 'images', 'services', @service.image))
				= image_tag 'placeholder.png', class: 'service-show-image'
			- else
				= image_tag "services/#{@service.image}", class: 'service-show-image'

		.col-xs-7.vcenter
			h3
				| Precio:
			p
				= "$#{@service.price}"
			h3
				| Invitación:
			p
				= @service.invitation
			h3
				| Descripción:
			p
				= @service.description

app/views/private/services_classifications/new.html.slim
header.new-services-classification-header
	.content-header-title
		h1
			= fa_icon 'cube'
			= " Nuevo servicio para #{@classification.title}"

.container_fluid.new-services-classification-content
	.row.new-service-classification-top-buttons
		.col-xs-12
			= link_to private_classifications_path, class: 'btn btn-turquoise'
				= fa_icon 'angle-double-left'
				|  Regresar

	.row
		.col-xs-offset-1.col-xs-10
			.panel
				.panel-heading.clearfix
					= fa_icon 'leaf'
					|  Servicios Disponibles
					= link_to new_private_service_path, class: 'btn btn-positive pull-right'
						= fa_icon 'plus'
				ul.list-group
					- @services.each do |service|
						li.list-group-item
							.row
								.col-xs-3.service-image-col
									- if service.image.blank? || !File.exist?(Rails.root.join('app', 'assets', 'images', 'services', service.image))
										= image_tag 'placeholder.png', class: 'service-image'
									- else
										= image_tag "services/#{service.image}", class: 'service-image'
								.col-xs-6.service-description-col
									h4
										= service.name
									= service.invitation
								.col-xs-3.service-actions-col
									= link_to private_services_classifications_path(service_id: service.id, classification_id: params[:classification_id]), method: :post, class: 'btn btn-amethyst'
										= fa_icon 'link'
										|  Enlazar